spring:
  application:
    name: web-service  # Identify this application


# HTTP Server
server:
  port: 4444   # HTTP (Tomcat) port

management:
  info:
    env:
      enabled: true
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  # -------------------------------------
  # Distributed Tracing Configuration
  # -------------------------------------
  tracing:
    enabled: true
    sampling:
      probability: 1.0

  zipkin:
    exporter:
      endpoint: http://localhost:9411/api/v2/spans

# Application info
info:
  app:
    name: Microservices Demo - Web Server
    description: This is a Web application
    version: 1.0.0